"""
Wrapper around the asyncio library, specialized to the bits that I understand and
use.
"""

# Standard library
import asyncio

# Local package
from .base import *

T = TypeVar("T")

class Event(asyncio.Event):
    @classmethod
    def field(cls) -> Event: ...

class StreamReader(asyncio.StreamReader): ...
class StreamWriter(asyncio.StreamWriter): ...

class Task(asyncio.Task[T]):
    @classmethod
    def field(cls) -> Task[Any]: ...
    @classmethod
    def create(
        cls: type[Task[T]], name: str, coro: Coroutine[Any, Any, T]
    ) -> Task[T]: ...

event_loop: asyncio.AbstractEventLoop

def run_coroutine_threadsafe(a: Awaitable[T]) -> T: ...
def gather(*aws: Awaitable[T]) -> Awaitable[list[T]]: ...
async def sleep(delay: float) -> None: ...
def call_later(seconds: float, f: Callable[[], None]) -> None: ...
def run_event_loop(main: Coroutine[Any, Any, T]) -> None: ...
async def wait_for(a: Awaitable[T], *, timeout: float) -> T | None: ...
async def open_connection(host: str, port: int) -> tuple[StreamReader, StreamWriter]: ...
