"""For controlling Apple TVs, using the pyatv library."""

# Local package
from .base import *
from .tv import TV

class ATV:
    """ "A controller for a single Apple TV."""

    # Navigation
    def home(self) -> None: ...
    def menu(self) -> None: ...
    def top_menu(self) -> None: ...

    # Arrows and select
    def down(self) -> None: ...
    def left(self) -> None: ...
    def right(self) -> None: ...
    def select(self) -> None: ...
    def up(self) -> None: ...

    # Media
    def next(self) -> None: ...
    def play_pause(self) -> None: ...
    def previous(self) -> None: ...
    def stop(self) -> None: ...
    def volume_down(self) -> None: ...
    def volume_up(self) -> None: ...
    def launch(self, bundle_id: str) -> None: ...
    def screensaver(self) -> None: ...
    def sleep(self) -> None: ...
    def wake(self) -> None: ...

@dataclass(slots=True)
class ATVs:
    """Controllers for all Apple TVs."""

    @classmethod
    def field(cls) -> ATVs: ...
    def atv(self, tv: TV) -> ATV: ...
    async def power_on(self) -> None: ...
    def set_should_send_commands_to_device(self, b: bool) -> None: ...
    async def synced(self) -> None: ...
    async def shutdown(self) -> None: ...
