"""
Manage the jtech device, by continually syncing the desired power and output.
"""

# Local package
from .base import *
from .jtech_output import JtechOutput

class JtechManager:
    @classmethod
    def field(cls) -> JtechManager: ...
    def power_on(self) -> None: ...
    def power_off(self) -> None: ...
    def set_output(self, desired_output: JtechOutput) -> None: ...
    def set_should_send_commands_to_device(self, b: bool) -> None: ...
    async def current_output(self) -> JtechOutput: ...
    def synced(self) -> Awaitable[None]:
        """Wait until the jtech is synced to desired power and output."""
