# Standard library
from pathlib import Path

# Local package
from .base import *
from .jtech import Jtech

class Power:
    ON: Power
    OFF: Power

class Multiviewer:
    def __init__(self) -> NoReturn: ...
    
    jtech: Jtech

async def create() -> Multiviewer: ...

async def shutdown(mv: Multiviewer) -> None: ...

async def load(p: Path) -> Multiviewer: ...

def save(mv: Multiviewer, p: Path) -> None: ...

def update_screen(mv: Multiviewer): ...

async def do_command_and_update_screen(mv: Multiviewer, args: list[str]) -> JSON: ...

async def describe_screen(mv: Multiviewer) -> str: ...

def describe_volume(mv: Multiviewer) -> str: ...

def power(mv: Multiviewer) -> Power: ...

async def power_on(mv: Multiviewer) -> None: ...

async def synced(mv: Multiviewer) -> None: ...