from __future__ import annotations

# Local package
from .atv import TV
from .base import JSON
from .jtech_output import JtechOutput

class Arrow:
    N: Arrow
    E: Arrow
    W: Arrow
    S: Arrow

class RemoteMode:
    APPLE_TV: RemoteMode
    MULTIVIEWER: RemoteMode

MULTIVIEWER: RemoteMode

class MvScreen:
    @classmethod
    def field(cls) -> MvScreen: ...
    remote_mode: RemoteMode
    def selected_tv(self) -> TV: ...
    def validate(self) -> None: ...
    def reset(self) -> None: ...
    def use_virtual_clock(self) -> None: ...
    def advance_clock(self, seconds: float) -> None: ...
    def render(self) -> JtechOutput: ...

    # Actions / button handling
    def power_on(self) -> None: ...
    def activate_tv(self) -> None: ...
    def deactivate_tv(self) -> None: ...
    def pressed_back(self) -> None: ...
    def pressed_play_pause(self) -> None: ...
    def toggle_submode(self) -> None: ...
    def pressed_arrow(self, arrow: Arrow) -> None: ...
    def pressed_select(self) -> None: ...
    def remote(self, tv: TV) -> JSON: ...
