# A volume delta is the net number of times we have sent volume-up (+1) and
#  volume-down (-1) to the TV.

# Local package
from .base import *
from .tv import TV

class Volume:
    @classmethod
    def field(cls) -> Volume: ...
    def adjust_volume(self, tv: TV, by: int) -> None: ...
    def set_for_tv(self, tv: TV) -> None: ...
    def unmute(self) -> None: ...
    def toggle_mute(self) -> None: ...
    def synced(self) -> Awaitable[None]: ...
    def describe_volume(self) -> str: ...
    def reset(self) -> None: ...
    def power_on(self) -> None: ...
    def set_should_send_commands_to_device(self, b: bool) -> None: ...
