# A volume delta is the net number of times we have sent volume-up (+1) and
#  volume-down (-1) to the TV.

# Local package
from .base import *

class Volume:
    @classmethod
    def field(cls) -> Volume: ...
    @classmethod
    async def create(cls) -> Volume: ...
    def set_volume_delta(self, to: int) -> None: ...
    def unmute(self) -> None: ...
    def toggle_mute(self) -> None: ...
    def synced(self) -> Awaitable[None]: ...
    def describe_volume(self) -> str: ...
    def reset(self) -> None: ...
